services:
  ansible:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - ~/.ssh:/root/.ssh:ro
    working_dir: /app
    dns:
      - 100.100.100.100
    dns_search:
      - tail252efc.ts.net
