---
EULA: "TRUE"
SERVER_NAME: "Minecraft Bedrock Server"
LEVEL_NAME: "EarthCraft"
GAMEMODE: "survival"
DIFFICULTY: "hard"
MAX_PLAYERS: 20
ONLINE_MODE: "true"
ALLOW_CHEATS: "false"
ALLOW_COMMANDS: "false"
ALLOW_FLIGHT: "false"
ALLOW_NETHER: "true"
ALLOW_END: "true"
