---
- name: Deploy complete Vertex Studio platform
  ansible.builtin.import_playbook: bootstrap.yaml

- name: Install Tailscale
  ansible.builtin.import_playbook: tailscale.yaml

- name: Install NVIDIA drivers
  ansible.builtin.import_playbook: nvidia.yaml

- name: Install NVIDIA Container Toolkit
  ansible.builtin.import_playbook: nvidia-container.yaml

- name: Deploy Stable Diffusion WebUI
  ansible.builtin.import_playbook: stable-diffusion.yaml

- name: Install Ollama LLM
  ansible.builtin.import_playbook: ollama.yaml

- name: Deploy Taiga
  ansible.builtin.import_playbook: taiga.yaml

- name: Deploy MkDocs
  ansible.builtin.import_playbook: mkdocs.yaml

- name: Deploy Prometheus and cAdvisor
  ansible.builtin.import_playbook: prometheus.yaml

- name: Deploy Loki and Promtail
  ansible.builtin.import_playbook: loki.yaml

- name: Deploy Grafana
  ansible.builtin.import_playbook: grafana.yaml

- name: Deploy Jenkins
  ansible.builtin.import_playbook: jenkins.yaml
