---
- name: Deploy complete Vertex Studio platform
  ansible.builtin.import_playbook: bootstrap.yaml

- name: Deploy Taiga
  ansible.builtin.import_playbook: taiga.yaml

- name: Deploy MkDocs
  ansible.builtin.import_playbook: mkdocs.yaml
