# group_vars/all.yml
---
prometheus_image: "prom/prometheus"
prometheus_version: "v3.9.1"

cadvisor_image: "gcr.io/cadvisor/cadvisor"
cadvisor_version: "v0.55.1"

jenkins_image: "jenkins/jenkins"
jenkins_version: "2.550"

minecraft_bedrock_image: "itzg/minecraft-bedrock-server"
minecraft_bedrock_version: "2026.2.0"
